default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: pizza_db

test:
  <<: *default
  database: pizza_db

production:
  <<: *default
  database: pizza_db