# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'grape'
gem 'pg'
gem 'csv'
gem 'sequel'
gem "webrick", "~> 1.7"
gem 'rack-cors'
